Refactor S3 client implementation
minio/minio-rs pull request #13
Opened 2022-08-16 05:41 UTC by balamurugana

Added below S3 APIs

* abort_multipart_upload()
* bucket_exists()
* complete_multipart_upload()
* create_multipart_upload()
* get_object()
* list_buckets()
* make_bucket()
* put_object()
* put_object_api()
* remove_bucket()
* remove_object()
* stat_object()
* upload_part()

Signed-off-by: Bala.FA <bala@minio.io>

2022-08-17 06:26 UTC, harshavardhana commented
@balamurugana can you add `github actions` workflow? and add tests here.

2022-08-17 08:35 UTC, balamurugana commented
> @balamurugana can you add `github actions` workflow? and add tests here.

It is added already https://github.com/minio/minio-rs/pull/13/files#diff-4ff0ade1283b13d85e91dc8f2c7de65755641d62dab43db4129bee31d50a40ca. But it is not kicking in!

2022-08-17 08:56 UTC, harshavardhana commented
> It is added already https://github.com/minio/minio-rs/pull/13/files#diff-4ff0ade1283b13d85e91dc8f2c7de65755641d62dab43db4129bee31d50a40ca. But it is not kicking in!

Can you "ammend" and push again?

2022-08-17 08:56 UTC, harshavardhana approved these changes

2022-08-17 08:57 UTC, harshavardhana requested changes

2022-08-17 08:57 UTC, harshavardhana commented on .github/workflow/ci.yml
> +        SERVER_ENDPOINT=https://localhost:9000/ ACCESS_KEY=minioadmin SECRET_KEY=minioadmin cargo test --verbose -- --nocapture
For Mint tests we used following style

```
SERVER_ENDPOINT=localhost:9000 ENABLE_HTTPS=1
```

2022-08-17 09:05 UTC, balamurugana commented on .github/workflow/ci.yml
> +        SERVER_ENDPOINT=https://localhost:9000/ ACCESS_KEY=minioadmin SECRET_KEY=minioadmin cargo test --verbose -- --nocapture
That works as well.

2022-08-20 22:09 UTC, harshavardhana approved these changes

2022-08-20 22:10 UTC, merged